apiVersion: apps/v1
kind: Deployment
metadata:
  name: homenamedeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepodname
  template:
    metadata:
      labels:
        app: homepodname
    spec:
      containers:
      - name: homecontainer
        image: guyluz11/cbj-rp-test:latest
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: myappservice
  labels:
    app: mservice
spec:
  selector:
    app: homepodname
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051
