apiVersion: v1
kind: Service
metadata:
  name: myappservice
  labels:
    app: mservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051
---
apiVersion: v1
kind: Pod
metadata:
  name: myapppod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: guyluz11/cbj-rp-test:latest
    ports:
    - containerPort: 50051
