apiVersion: apps/v1
kind: Deployment
metadata:
  name: namedeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namepod
  template:
    metadata:
      labels:
        app: namepod
    spec:
      containers:
      - name: homecontainer
        image: guyluz11/cbj-rp-test:latest
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: nameservice
  labels:
    app: nameservicelabel
spec:
  selector:
    app: namepod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051
