

apiVersion: v1
kind: Service
metadata:
  name: homeservice-one-service
  labels:
    app: homeservice-one-label
spec:
  selector:
    app: homeservice-one
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
