

apiVersion: v1
kind: Service
metadata:
  name: nameservice # this one needs to change dynamically without -
  labels:
    app: homeservice-one-label
spec:
  selector:
    app: pod-name # this one needs to change dynamically
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
