
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-pipes-deployment
  labels:
    app: pod-name # this one needs to change dynamically
spec:
#  replicas: 1
  selector:
    matchLabels:
      app: pod-name
  template:
    metadata:
      labels:
        app: pod-name
    spec:
      containers:
      - name: remote-pipes
        image: guyluz11/cbj-rp-test
        ports:
        - containerPort: 50056