

apiVersion: v1
kind: Service
metadata:
  name: remote-pipes-loadbalancer
#  annotations:
#    service.beta.kubernetes.io/linode-loadbalancer-default-proxy-protocol: v2
spec:
#  clusterIP: None # Headless services
  selector:
    app: remote-pipes
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 100
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: LoadBalancer
